// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: melt.proto

package cashurpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuoteBolt11StateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuoteId string `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
}

func (x *GetQuoteBolt11StateRequest) Reset() {
	*x = GetQuoteBolt11StateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuoteBolt11StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteBolt11StateRequest) ProtoMessage() {}

func (x *GetQuoteBolt11StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteBolt11StateRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteBolt11StateRequest) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuoteBolt11StateRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type PostMeltQuoteBolt11Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Unit    UnitType `protobuf:"varint,2,opt,name=unit,proto3,enum=UnitType" json:"unit,omitempty"`
}

func (x *PostMeltQuoteBolt11Request) Reset() {
	*x = PostMeltQuoteBolt11Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMeltQuoteBolt11Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeltQuoteBolt11Request) ProtoMessage() {}

func (x *PostMeltQuoteBolt11Request) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeltQuoteBolt11Request.ProtoReflect.Descriptor instead.
func (*PostMeltQuoteBolt11Request) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{1}
}

func (x *PostMeltQuoteBolt11Request) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *PostMeltQuoteBolt11Request) GetUnit() UnitType {
	if x != nil {
		return x.Unit
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

type PostMeltQuoteStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostMeltQuoteStateResponse) Reset() {
	*x = PostMeltQuoteStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMeltQuoteStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeltQuoteStateResponse) ProtoMessage() {}

func (x *PostMeltQuoteStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeltQuoteStateResponse.ProtoReflect.Descriptor instead.
func (*PostMeltQuoteStateResponse) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{2}
}

type PostMeltQuoteBolt11Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quote      string `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	Amount     uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeReserve uint64 `protobuf:"varint,3,opt,name=fee_reserve,json=feeReserve,proto3" json:"fee_reserve,omitempty"`
	Paid       bool   `protobuf:"varint,4,opt,name=paid,proto3" json:"paid,omitempty"`
	Expiry     int64  `protobuf:"varint,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *PostMeltQuoteBolt11Response) Reset() {
	*x = PostMeltQuoteBolt11Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMeltQuoteBolt11Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeltQuoteBolt11Response) ProtoMessage() {}

func (x *PostMeltQuoteBolt11Response) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeltQuoteBolt11Response.ProtoReflect.Descriptor instead.
func (*PostMeltQuoteBolt11Response) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{3}
}

func (x *PostMeltQuoteBolt11Response) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *PostMeltQuoteBolt11Response) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PostMeltQuoteBolt11Response) GetFeeReserve() uint64 {
	if x != nil {
		return x.FeeReserve
	}
	return 0
}

func (x *PostMeltQuoteBolt11Response) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *PostMeltQuoteBolt11Response) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type PostMeltBolt11Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inputs []*Proof `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Quote  string   `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *PostMeltBolt11Request) Reset() {
	*x = PostMeltBolt11Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMeltBolt11Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeltBolt11Request) ProtoMessage() {}

func (x *PostMeltBolt11Request) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeltBolt11Request.ProtoReflect.Descriptor instead.
func (*PostMeltBolt11Request) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{4}
}

func (x *PostMeltBolt11Request) GetInputs() []*Proof {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *PostMeltBolt11Request) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

type PostMeltBolt11Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paid            bool   `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	PaymentPreimage string `protobuf:"bytes,2,opt,name=payment_preimage,json=paymentPreimage,proto3" json:"payment_preimage,omitempty"` // This field is optional and can be null.
}

func (x *PostMeltBolt11Response) Reset() {
	*x = PostMeltBolt11Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_melt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMeltBolt11Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeltBolt11Response) ProtoMessage() {}

func (x *PostMeltBolt11Response) ProtoReflect() protoreflect.Message {
	mi := &file_melt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeltBolt11Response.ProtoReflect.Descriptor instead.
func (*PostMeltBolt11Response) Descriptor() ([]byte, []int) {
	return file_melt_proto_rawDescGZIP(), []int{5}
}

func (x *PostMeltBolt11Response) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *PostMeltBolt11Response) GetPaymentPreimage() string {
	if x != nil {
		return x.PaymentPreimage
	}
	return ""
}

var File_melt_proto protoreflect.FileDescriptor

var file_melt_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6d, 0x69,
	0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x42, 0x6f, 0x6c, 0x74, 0x31, 0x31, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x22,
	0x55, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x42, 0x6f, 0x6c, 0x74, 0x31, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65,
	0x6c, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x1b, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x6c,
	0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x42, 0x6f, 0x6c, 0x74, 0x31, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x65, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x65, 0x65, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x70, 0x61, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22,
	0x4d, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x6c, 0x74, 0x42, 0x6f, 0x6c, 0x74, 0x31,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x52, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x57,
	0x0a, 0x16, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x6c, 0x74, 0x42, 0x6f, 0x6c, 0x74, 0x31, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x72, 0x65, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x30, 0x42, 0x09, 0x4d, 0x65, 0x6c, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x6e, 0x6f, 0x73, 0x68, 0x2f, 0x67, 0x6f, 0x6e, 0x75, 0x74, 0x73,
	0x2f, 0x63, 0x61, 0x73, 0x68, 0x75, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_melt_proto_rawDescOnce sync.Once
	file_melt_proto_rawDescData = file_melt_proto_rawDesc
)

func file_melt_proto_rawDescGZIP() []byte {
	file_melt_proto_rawDescOnce.Do(func() {
		file_melt_proto_rawDescData = protoimpl.X.CompressGZIP(file_melt_proto_rawDescData)
	})
	return file_melt_proto_rawDescData
}

var file_melt_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_melt_proto_goTypes = []interface{}{
	(*GetQuoteBolt11StateRequest)(nil),  // 0: GetQuoteBolt11StateRequest
	(*PostMeltQuoteBolt11Request)(nil),  // 1: PostMeltQuoteBolt11Request
	(*PostMeltQuoteStateResponse)(nil),  // 2: PostMeltQuoteStateResponse
	(*PostMeltQuoteBolt11Response)(nil), // 3: PostMeltQuoteBolt11Response
	(*PostMeltBolt11Request)(nil),       // 4: PostMeltBolt11Request
	(*PostMeltBolt11Response)(nil),      // 5: PostMeltBolt11Response
	(UnitType)(0),                       // 6: UnitType
	(*Proof)(nil),                       // 7: Proof
}
var file_melt_proto_depIdxs = []int32{
	6, // 0: PostMeltQuoteBolt11Request.unit:type_name -> UnitType
	7, // 1: PostMeltBolt11Request.inputs:type_name -> Proof
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_melt_proto_init() }
func file_melt_proto_init() {
	if File_melt_proto != nil {
		return
	}
	file_mint_proto_init()
	file_proofs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_melt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuoteBolt11StateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_melt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMeltQuoteBolt11Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_melt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMeltQuoteStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_melt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMeltQuoteBolt11Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_melt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMeltBolt11Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_melt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMeltBolt11Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_melt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_melt_proto_goTypes,
		DependencyIndexes: file_melt_proto_depIdxs,
		MessageInfos:      file_melt_proto_msgTypes,
	}.Build()
	File_melt_proto = out.File
	file_melt_proto_rawDesc = nil
	file_melt_proto_goTypes = nil
	file_melt_proto_depIdxs = nil
}
