// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: mint.proto

package cashurpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitType int32

const (
	UnitType_UNIT_TYPE_UNSPECIFIED UnitType = 0
	UnitType_UNIT_TYPE_SAT         UnitType = 1
)

// Enum value maps for UnitType.
var (
	UnitType_name = map[int32]string{
		0: "UNIT_TYPE_UNSPECIFIED",
		1: "UNIT_TYPE_SAT",
	}
	UnitType_value = map[string]int32{
		"UNIT_TYPE_UNSPECIFIED": 0,
		"UNIT_TYPE_SAT":         1,
	}
)

func (x UnitType) Enum() *UnitType {
	p := new(UnitType)
	*p = x
	return p
}

func (x UnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_mint_proto_enumTypes[0].Descriptor()
}

func (UnitType) Type() protoreflect.EnumType {
	return &file_mint_proto_enumTypes[0]
}

func (x UnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitType.Descriptor instead.
func (UnitType) EnumDescriptor() ([]byte, []int) {
	return file_mint_proto_rawDescGZIP(), []int{0}
}

type PostMintQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Amount uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Unit   UnitType `protobuf:"varint,3,opt,name=unit,proto3,enum=UnitType" json:"unit,omitempty"`
}

func (x *PostMintQuoteRequest) Reset() {
	*x = PostMintQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMintQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMintQuoteRequest) ProtoMessage() {}

func (x *PostMintQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMintQuoteRequest.ProtoReflect.Descriptor instead.
func (*PostMintQuoteRequest) Descriptor() ([]byte, []int) {
	return file_mint_proto_rawDescGZIP(), []int{0}
}

func (x *PostMintQuoteRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PostMintQuoteRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PostMintQuoteRequest) GetUnit() UnitType {
	if x != nil {
		return x.Unit
	}
	return UnitType_UNIT_TYPE_UNSPECIFIED
}

type PostMintQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quote   string `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	Request string `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Paid    bool   `protobuf:"varint,3,opt,name=paid,proto3" json:"paid,omitempty"`
	Expiry  int64  `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (x *PostMintQuoteResponse) Reset() {
	*x = PostMintQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMintQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMintQuoteResponse) ProtoMessage() {}

func (x *PostMintQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMintQuoteResponse.ProtoReflect.Descriptor instead.
func (*PostMintQuoteResponse) Descriptor() ([]byte, []int) {
	return file_mint_proto_rawDescGZIP(), []int{1}
}

func (x *PostMintQuoteResponse) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *PostMintQuoteResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *PostMintQuoteResponse) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *PostMintQuoteResponse) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type PostMintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Quote   string            `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	Outputs []*BlindedMessage `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *PostMintRequest) Reset() {
	*x = PostMintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMintRequest) ProtoMessage() {}

func (x *PostMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMintRequest.ProtoReflect.Descriptor instead.
func (*PostMintRequest) Descriptor() ([]byte, []int) {
	return file_mint_proto_rawDescGZIP(), []int{2}
}

func (x *PostMintRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PostMintRequest) GetQuote() string {
	if x != nil {
		return x.Quote
	}
	return ""
}

func (x *PostMintRequest) GetOutputs() []*BlindedMessage {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type PostMintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signatures []*BlindedSignature `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *PostMintResponse) Reset() {
	*x = PostMintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMintResponse) ProtoMessage() {}

func (x *PostMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMintResponse.ProtoReflect.Descriptor instead.
func (*PostMintResponse) Descriptor() ([]byte, []int) {
	return file_mint_proto_rawDescGZIP(), []int{3}
}

func (x *PostMintResponse) GetSignatures() []*BlindedSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

var File_mint_proto protoreflect.FileDescriptor

var file_mint_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x14,
	0x50, 0x6f, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x09, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x22, 0x73, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x70, 0x61, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x22, 0x6a, 0x0a, 0x0f, 0x50, 0x6f, 0x73, 0x74,
	0x4d, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6c, 0x69,
	0x6e, 0x64, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42,
	0x6c, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2a, 0x38, 0x0a, 0x08, 0x55,
	0x6e, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x49, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x49, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x53, 0x41, 0x54, 0x10, 0x01, 0x42, 0x30, 0x42, 0x09, 0x4d, 0x69, 0x6e, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6c, 0x6e, 0x6f, 0x73, 0x68, 0x2f, 0x67, 0x6f, 0x6e, 0x75, 0x74, 0x73, 0x2f, 0x63,
	0x61, 0x73, 0x68, 0x75, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mint_proto_rawDescOnce sync.Once
	file_mint_proto_rawDescData = file_mint_proto_rawDesc
)

func file_mint_proto_rawDescGZIP() []byte {
	file_mint_proto_rawDescOnce.Do(func() {
		file_mint_proto_rawDescData = protoimpl.X.CompressGZIP(file_mint_proto_rawDescData)
	})
	return file_mint_proto_rawDescData
}

var file_mint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mint_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mint_proto_goTypes = []interface{}{
	(UnitType)(0),                 // 0: UnitType
	(*PostMintQuoteRequest)(nil),  // 1: PostMintQuoteRequest
	(*PostMintQuoteResponse)(nil), // 2: PostMintQuoteResponse
	(*PostMintRequest)(nil),       // 3: PostMintRequest
	(*PostMintResponse)(nil),      // 4: PostMintResponse
	(*BlindedMessage)(nil),        // 5: BlindedMessage
	(*BlindedSignature)(nil),      // 6: BlindedSignature
}
var file_mint_proto_depIdxs = []int32{
	0, // 0: PostMintQuoteRequest.unit:type_name -> UnitType
	5, // 1: PostMintRequest.outputs:type_name -> BlindedMessage
	6, // 2: PostMintResponse.signatures:type_name -> BlindedSignature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mint_proto_init() }
func file_mint_proto_init() {
	if File_mint_proto != nil {
		return
	}
	file_message_proto_init()
	file_signature_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMintQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMintQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mint_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mint_proto_goTypes,
		DependencyIndexes: file_mint_proto_depIdxs,
		EnumInfos:         file_mint_proto_enumTypes,
		MessageInfos:      file_mint_proto_msgTypes,
	}.Build()
	File_mint_proto = out.File
	file_mint_proto_rawDesc = nil
	file_mint_proto_goTypes = nil
	file_mint_proto_depIdxs = nil
}
