// Code generated by protoc-gen-cashu. DO NOT EDIT.
package cashurpc

import (
	"encoding/base64"
	"encoding/json"
)

func (x *TokenV3) ToString() string {
	jsonBytes, err := json.Marshal(x)
	if err != nil {
		panic(err)
	}
	token := base64.URLEncoding.EncodeToString(jsonBytes)
	return "cashuA" + token
}
func (t *TokenV3) TotalAmount() uint64 {
	var totalAmount uint64 = 0
	for _, tokenProof := range t.Token {
		for _, proof := range tokenProof.Proofs {
			totalAmount += proof.Amount
		}
	}
	return totalAmount
}
